server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/LiveTalk

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  web:
    socket:
      stomp:
        broker:
          relay:
            enabled: true
            relay-host: localhost
            relay-port: 61613
            client-login: guest
            client-passcode: guest
            heartbeat:
              server: 60 * 60000    # Send heartbeat every 10 seconds
              client: 60 * 60000    # Expect heartbeat every 10 seconds


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true