server:
  port: 9090

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: ModerationService
          uri: lb://MODERATIONSERVICE
          predicates:
            - Path=/moderation/**
        - id: RoomService
          uri: lb://ROOMSERVICE
          predicates:
            - Path=/rooms/**
        - id: NotificationService
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notification/**
        - id: ChatService
          uri: lb://CHATSERVICE
          predicates:
            - Path=/chat/**
        - id: PaymentGatewayService
          uri: lb://PAYMENTGATEWAYSERVICE
          predicates:
            - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"