server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: ModerationService
          uri: lb://MODERATION-SERVICE
          predicates:
            - Path=/moderation/**
        - id: RoomService
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/rooms/**
        - id: NotificationService
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: ChatService
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
        - id: PaymentGatewayService
          uri: lb://PAYMENT-GATEWAY-SERVICE
          predicates:
            - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"