spring.application.name=moderation-service
server.port=8084
#mongo
spring.data.mongodb.uri=mongodb://mongo:27017/LiveTalk
spring.data.mongodb.auto-index-creation=true
#Eureka
eureka.client.serviceUrl.defaultZone=http://eureka-registry:8761/eureka
eureka.instance.prefer-ip-address=true