spring.application.name=ModerationService
server.port=8084
spring.data.mongodb.uri=mongodb://localhost:27017/LiveTalk
spring.data.mongodb.auto-index-creation=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true