server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/LiveTalk

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-registry:8761/eureka
  instance:
    prefer-ip-address: true