chat-service:
  url: http://localhost:8083

stripe:
  secretKey: ${STRIPE_SECRETKEY}

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true