chat-service:
  url: http://localhost:8083

stripe:
  secretKey: sk_test_51Rep13FRADPNlFI8ngEUo0Vtd71Tu6ceslJUzbJfBZwn3IDfrOPfWfkC73tAyBiO8GtjnCClFLVrV4kT3mxIDvmd00uRIhm6gu

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true