chat-service:
  url: http://chat-service:8083

stripe:
  secretKey: ${STRIPE_SECRETKEY}

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-registry:8761/eureka
  instance:
    prefer-ip-address: true